#!/usr/bin/env bash
WGET_PATH="/usr/local/bin/wget"
TITLE="translation"
text=$(pbpaste | sed "s/[\"'<>]//g")
encodedText=$(php -r "echo urlencode(\"$text\");")
url="http://translate.google.com/translate_a/t?client=t&text=$encodedText&sl=auto&tl=ru"
response=$($WGET_PATH -U "Mozilla/5.0" -qO - $url)
result=$(echo $response | sed 's/\[\[\[\"//' | cut -d \" -f 1)

osascript -e "display notification \"$result\" with title \"$TITLE\""
